{
  description = "My first NixOS Flake!";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs, ... }@inputs: {
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        /etc/nixos/hardware-configuration.nix # The autogenerated hardware configuration
        ./core-configuration.nix # Essential stuff like networking, desktop, etc.
      ];
    };
  };
}