{
  description = "My first NixOS Flake!";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  outputs = { self, nixpkgs, ... }@inputs: {
    nixosConfigurations.alexjf = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # Autogenerated hardware configuration
        (import /etc/nixos/hardware-configuration.nix)
        # Manual Configuration
        ./system-configuration/networking
        ./system-configuration/user
        ./system-configuration/audio
        ./system-configuration/desktop
        ./system-configuration/misc-configuration.nix
        ./system-configuration/universal-packages.nix
        # Packages
        ./packages/universal-packages
      ];
    };
  };
}